// <auto-generated />
using Chapter3Project.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Chapter3Project.Migrations
{
    [DbContext(typeof(SetContext))]
    partial class SetContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Chapter3Project.Models.ClothingSet", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SmiskiType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ClothingSet");
                });

            modelBuilder.Entity("Chapter3Project.Models.Set", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SmiskiType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("sets");

                    b.HasData(
                        new
                        {
                            Id = "M",
                            SetName = "Moving",
                            SmiskiType = "Boxes Smiski"
                        },
                        new
                        {
                            Id = "D",
                            SetName = "Dressing",
                            SmiskiType = "Sweater Smiski"
                        },
                        new
                        {
                            Id = "B",
                            SetName = "Bath",
                            SmiskiType = "Shower Smiski"
                        },
                        new
                        {
                            Id = "Y",
                            SetName = "Yoga",
                            SmiskiType = "Grounded Smiski"
                        },
                        new
                        {
                            Id = "E",
                            SetName = "Exercise",
                            SmiskiType = "Sit Ups Smiski"
                        },
                        new
                        {
                            Id = "C",
                            SetName = "Cheer",
                            SmiskiType = "Pom Pom Smiski"
                        },
                        new
                        {
                            Id = "W",
                            SetName = "Work",
                            SmiskiType = "Laptop Smiski"
                        },
                        new
                        {
                            Id = "L",
                            SetName = "Living",
                            SmiskiType = "Flute Smiski"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
